package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/heschmat/MemoBin/internal/assert"
)

func TestPing(t *testing.T) {
	// Initialize a new `httptest.ResponseRecorder`
	rr := httptest.NewRecorder()

	// Initialize a new dummy `http.Request`
	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// Call the *ping* handler function.
	ping(rr, r)

	// Get the `http.Response` generated by the ping handler.
	rs := rr.Result()

	// 1. Check the status code written by the ping handler is 200.
	assert.Equal(t, rs.StatusCode, http.StatusOK)

	// 2. Check the response body written by the ping handler equals "OK"
	defer rs.Body.Close()
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	body = bytes.TrimSpace(body)
	assert.Equal(t, string(body), "OK")
}
